/*
 * File: app/store/AgentGridJsonStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.store.AgentGridJsonStore', {
    extend: 'Ext.data.Store',

    requires: [
        'app.model.AgentGridModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            remoteSort: true,
            storeId: 'MyJsonStore',
            model: 'app.model.AgentGridModel',
            pageSize: 30,
            fields: [
                {
                    name: 'agentId'
                },
                {
                    name: 'ip'
                },
                {
                    name: 'agentVersion'
                },
                {
                    name: 'gateway'
                },
                {
                    name: 'agentStatus'
                },
                {
                    name: 'agentHostStatus'
                }
            ],
            proxy: {
                type: 'ajax',
                extraParams: {
                    agentId: '',
                    ip: '',
                    os:''
                },
                url: 'findAgentGridInfo',
                reader: {
                    type: 'json',
                    root: 'root',
                    totalProperty: 'activeTotal'
                }
            },
            listeners : {  
            	beforeload: function(store, operation, options){
            		//设置参数
            		var inOs = Ext.alarm.os;
		    		store.proxy.extraParams.os=inOs;
		    		
            	}
            }
        }, cfg)]);
    }
});