/*
 * File: app/store/HostPingStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.store.HostPingStore', {
    extend: 'Ext.data.Store',

    requires: [
        'app.model.HostPingModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'app.model.HostPingModel',
            remoteSort: true,
            storeId: 'MyJsonStore',
            pageSize: 30,
            proxy: {
                type: 'ajax',
                extraParams: {
                    ip: ''
                },
                url: 'getHostPing',
                reader: {
                    type: 'json',
                    root: 'root',
                    totalProperty: 'total'
                }
            },
            fields: [
                {
                    name: 'agentId'
                },
                {
                    name: 'ip'
                },
                {
                    name: 'os'
                },
                {
                    name: 'pingTime'
                },
                {
                    name: 'pingStatus'
                },
                {
                    name: 'realip'
                }
            ]
        }, cfg)]);
    }
});