/*
 * File: app/../view/MainFrame.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('main.view.MainFrame', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.MainFrame',

    id: 'mainFrame',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    border: 0,
                    height: 98,
                    id: 'topPanel',
                    layout: {
                        type: 'fit'
                    },
                    bodyBorder: false,
                    items: [
                        {
                            xtype: 'panel',
                            border: 0,
                            height: 70,
                            id: 'mainMenuPanel',
                            autoScroll: false,
                            layout: {
                                type: 'absolute'
                            },
                            bodyBorder: false,
                            bodyStyle: 'background:url(\''+AVMON_GLOBAL_HEADER_IMAGE+'\')',
                            items: [
                                {
                                    xtype: 'container',
                                    x: 960,
                                    y: 50,
                                    height: 20,
                                    html: '注销',
                                    id: 'loginInfoPanel',
                                    width: 230
                                }
                                /*
                                 ,
                                {
                                    xtype: 'label',
                                    x: 710,
                                    y: 44,
                                    baseCls: 'button1-back',
                                    height: 26,
                                    id: 'labelMonitorCenter',
                                    overCls: 'button1-over',
                                    width: 110,
                                    text: '监控中心'
                                },
                                {
                                    xtype: 'label',
                                    x: 821,
                                    y: 44,
                                    baseCls: 'button1-back',
                                    height: 26,
                                    id: 'labelPollingCenter',
                                    overCls: 'button1-over',
                                    width: 110,
                                    text: '巡检中心'
                                }
                                //*/
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'panel',
                            dock: 'bottom',
                            border: 0,
                            height: 28,
                            id: 'subMenuPanel',
                            layout: {
                                type: 'column'
                            },
                            bodyStyle: 'background:url(\'main/images/menu_back.png\')',
                            items: [
                                {
                                    xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu1',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu1_hidden,
                                    text: '告警监控'
                                },
                                {
                                    xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu2',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu2_hidden,
                                    text: '实时性能'
                                },
                                {
                                    xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu7',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu7_hidden,
                                    text: '性能分析'
                                },
                                {
                                    xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu8',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu8_hidden,
                                    text: '实时状态'
                                },
                                {
                                    xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu3',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu3_hidden,
                                    text: '查询与报表'
                                },
                                                              
                                //add by ted start
                                {
                                	xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu11',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu11_hidden,
                                    text: '资源视图'
                                },
                                //--add by ted end
                                //add by ted start
                                {
                                	xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu13',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu13_hidden,
                                    text: '视图编辑'
                                },
                                {
                                	xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu14',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu14_hidden,
                                    text: '类资源管理'
                                },
                                {
                                	xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu16',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu16_hidden,
                                    text: '关系资源管理'
                                },
                                {
                                	xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu12',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu12_hidden,
                                    text: '类模型定义'
                                },
                                {
                                	xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu10',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu10_hidden,
                                    text: '类模型定义'
                                },
                                
                                {
                                	xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu15',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu15_hidden,
                                    text: '关系建模定义'
                                },                          
                                                              
                                {
                                	xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu17',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu17_hidden,
                                    text: '资源查询管理'
                                },
                                //--add by ted end
                                //add by mark start
                                
                                //--add by mark end
                                {
                                    xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu4',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu4_hidden,
                                    text: '配置管理'
                                },
                                {
                                    xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu5',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu5_hidden,
                                    text: '部署管理'
                                },
                                {
                                    xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu6',
                                    overCls: 'button2-over',
                                    width: 114,
                                    hidden:mainFrame_labMenu6_hidden,
                                    text: '系统管理'
                                },
                                {
                                    xtype: 'label',
                                    baseCls: 'button2-back',
                                    height: 28,
                                    id: 'mainFrame_labMenu9',
                                    overCls: 'button2-over',
                                    width: 113,
                                    hidden:mainFrame_labMenu9_hidden,
                                    text: '网络巡检配置'
                                }
                            ]
                        }
                    ],
                    listeners: {
                        afterlayout: {
                            fn: me.onTopPanelAfterLayout,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'container',
                    region: 'center',
                    border: 0,
                    id: 'mainFrame_TabPanel',
                    layout: {
                        type: 'card'
                    },
                    items: [
                        {
                            xtype: 'container',
                            html: 'loading...',
                            id: 'tabAlarm'
                        },{
                            xtype: 'container',
                            html: 'loading...',
                            id: 'tabSim'
                        },
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'fit'
                            },
                            //html: 'loading...',
                            id: 'tabPerformance'
                        },
                        {
                            xtype: 'panel',
                            id: 'tabConfig',
                            layout: {
                                type: 'fit'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: {
                                        type: 'border'
                                    },
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'treepanel',
                                            region: 'west',
                                            split: true,
                                            itemId: 'configMenuTree',
                                            width: 250,
                                            collapsible: true,
                                            title: 'Menu',
                                            store: Ext.create('main.store.ConfigMenus'),
                                            rootVisible: false,
                                            viewConfig: {

                                            },
                                            listeners: {
                                                select: {
                                                    fn: me.onMenuTreeSelect1,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'panel',
                                            region: 'center',
                                            frame: true,
                                            id: 'configContent',
                                            title: ''
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            html: 'loading...',
                            id: 'tabDeploy'
                        },
                        {
                            xtype: 'panel',
                            id: 'tabSystem',
                            layout: {
                                type: 'fit'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: {
                                        type: 'border'
                                    },
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'treepanel',
                                            region: 'west',
                                            split: true,
                                            itemId: 'systemMenuTree',
                                            width: 250,
                                            collapsible: true,
                                            title: 'Menu',
                                            store: Ext.create('main.store.SystemMenus'),
                                            rootVisible: false,
                                            viewConfig: {

                                            },
                                            listeners: {
                                                select: {
                                                    fn: me.onSystemMenuTreeSelect,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'panel',
                                            region: 'center',
                                            id: 'systemContent',
                                            title: ''
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'tabReport',
                            layout: {
                                type: 'fit'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: {
                                        type: 'border'
                                    },
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'treepanel',
                                            region: 'west',
                                            split: true,
                                            itemId: 'reportMenuTree',
                                            width: 250,
                                            collapsible: true,
                                            title: 'Menu',
                                            store: Ext.create('main.store.ReportMenus'),
                                            rootVisible: false,
                                            viewConfig: {

                                            },
                                            listeners: {
                                                select: {
                                                    fn: me.onMenuTreeSelect11,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'panel',
                                            region: 'center',
                                            id: 'reportContent',
                                            title: ''
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'tabKpiPerformance',
                            layout: {
                                type: 'fit'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: {
                                        type: 'border'
                                    },
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'treepanel',
                                            region: 'west',
                                            split: true,
                                            itemId: 'performanceTree',
                                            width: 250,
                                            collapsible: true,
                                            title: 'Menu',
                                            store: Ext.create('main.store.PerformanceMenus'),
                                            rootVisible: false,
                                            viewConfig: {

                                            },
                                            listeners: {
                                                select: {
                                                    fn: me.onPerformanceTreeSelect,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'panel',
                                            region: 'center',
                                            id: 'performanceContent',
                                            title: ''
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                        	xtype: 'panel',
                            id: 'tabPolling',
                            layout: {
                                type: 'fit'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: {
                                        type: 'border'
                                    },
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'treepanel',
                                            region: 'west',
                                            split: true,
                                            itemId: 'pollingTree',
                                            width: 250,
                                            collapsible: true,
                                            title: 'Menu',
                                            store: Ext.create('main.store.PollingMenus'),
                                            rootVisible: false,
                                            viewConfig: {

                                            },
                                            listeners: {
                                                select: {
                                                    fn: me.onPollingTreeSelect,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'panel',
                                            region: 'center',
                                            id: 'pollingContent',
                                            title: ''
                                        }
                                    ]
                                }
                            ]
                        },
                        //add by mark start
                        {
                            xtype: 'panel',
                            html: 'loading...',
                            id: 'tabEquipmentCenter'
                        },
                        //--add by mark end
                        //add by ted start
                        {
                            xtype: 'panel',
                            html: 'loading...',
                            id: 'tabModelView'
                        },
                        //--add by ted end
                        //add by mark start
                        {
                            xtype: 'panel',
                            html: 'loading...',
                            id: 'tabClassMgr'
                        },
                        //--add by mark end
                        //add by ted start
                        {
                            xtype: 'panel',
                            html: 'loading...',
                            id: 'tabModelStudio'
                        },
                        //--add by ted end
                      //add by ted start
                        {
                            xtype: 'panel',
                            html: 'loading...',
                            id: 'tabRelTypeMgr'
                        },
                        //--add by ted end
                      //add by ted start
                        {
                            xtype: 'panel',
                            html: 'loading...',
                            id: 'tabRelMgr'
                        },
                        //--add by ted end

                      //add by ted start
                        {
                            xtype: 'panel',
                            html: 'loading...',
                            id: 'tabCIMgr'
                        },
                        {
                            xtype: 'panel',
                            html: 'loading...',
                            id: 'tabSearchMgr'
                        },
                        {
                            xtype: 'toolbar'
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: {
                    fn: me.onMainFrameAfterRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onTopPanelAfterLayout: function(abstractcontainer, layout, options) {
        //Ext.getCmp("labelMonitorCenter").setPosition(Ext.getCmp("topPanel").getWidth()-460,44);
        //Ext.getCmp("labelPollingCenter").setPosition(Ext.getCmp("topPanel").getWidth()-350,44);
        Ext.getCmp("loginInfoPanel").setPosition(Ext.getCmp("topPanel").getWidth()-230,50);
    },

    onMenuTreeSelect1: function(selModel, record, index, options) {

        Ext.getCmp('configContent').body.update('<iframe scrolling="auto" frameborder="0" width="100%" height="100%" src="'+record.get("url")+'"></iframe>');

    },

    onSystemMenuTreeSelect: function(selModel, record, index, options) {

        Ext.getCmp('systemContent').body.update('<iframe scrolling="auto" frameborder="0" width="100%" height="100%" src="'+record.get("url")+'"></iframe>');

    },
    
    onPerformanceTreeSelect: function(selModel, record, index, options) {

        Ext.getCmp('performanceContent').body.update('<iframe scrolling="auto" frameborder="0" width="100%" height="100%" src="'+record.get("url")+'"></iframe>');

    },
    
    onPollingTreeSelect: function(selModel, record, index, options) {

        Ext.getCmp('pollingContent').body.update('<iframe scrolling="auto" frameborder="0" width="100%" height="100%" src="'+record.get("url")+'"></iframe>');

    },

    onMenuTreeSelect11: function(selModel, record, index, options) {

        Ext.getCmp('reportContent').body.update('<iframe scrolling="auto" frameborder="0" width="100%" height="100%" src="'+record.get("url")+'"></iframe>');

    },

    onMainFrameAfterRender: function(abstractcomponent, options) {

        Ext.getCmp('loginInfoPanel').update('当前用户：'+ Ext.avmon.loginUserName+ '&nbsp;&nbsp;<a href=../logout>[注销]</a>&nbsp;&nbsp;<a href="#" onclick="Ext.modifyPwd()">[修改密码]</a>');



        //register label-menu click event
        Ext.each(Ext.getCmp("mainMenuPanel").query("label"),function(item){

            Ext.fly(item.el).on('click',Ext.avmon.mainMenuClick);

        });

        Ext.each(Ext.getCmp("subMenuPanel").query("label"),function(item){

            Ext.fly(item.el).on('click',Ext.avmon.subMenuClick);

        });


        Ext.avmon.mainMenuClick(null,{id:"labelMonitorCenter"});

    }

});