/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({

    requires: [
        'MyApp.view.MyViewport',
        'MyApp.view.searchWindow',
        'MyApp.view.forwardAlarmWindow'
    ],
    models: [
        'treeModel',
        'activeAlarmModel',
        'historyAlarmModel',
        'pastRecordsModel',
        'resultModel'
    ],
    stores: [
        'treeStore',
        'avtiveAlarmStore',
        'historyAlarmStore',
        'pastRecordsStore',
        'resultStore',
        'RecipientStore'
    ],
    views: [
        'MyViewport'
    ],
    autoCreateViewport: true,
    name: 'MyApp',

    launch: function() {
        Ext.modelView.application = this;


     // 统计信息
        Ext.Ajax.request({
            url: 'testRMI',
//            params: {mo:Ext.mainEngine.moId},
            success: function(response, opts) {
                var obj = Ext.decode(response.responseText);
                console.log("invoke successfully." + obj);
//                Ext.getCmp("courseForm").getForm().setValues(obj);
            },
            failure: function(response, opts) {
                if(console && console.log){
                    console.log("load dashboard-mem error!");
                }
            }
        });
        
        
//        // 隐藏右边告警信息面板
//        var tabPanel = Ext.getCmp('tabPanel');
//        tabPanel.hide();
//
//        // 隐藏下部历史告警面板
//        var historyAlarm = Ext.getCmp('historyAlarm');
//        historyAlarm.hide();
//
//        // 从其他页面跳转过来
//        if (Ext.alarm.moId != null && Ext.alarm.moId != 'null' && Ext.alarm.moId != '') {
//
//            // 根据传入moId取得树节点Id
//            Ext.Ajax.request({  
//                url:'getTreeIdByMoId',  
//                params:{  
//                    //传递参数  
//                    moId:Ext.alarm.moId
//                },  
//                async : false,
//                success:function(response, options){   
//                    var treeObject = Ext.JSON.decode(response.responseText);
//
//                    var treeId = treeObject.treeId;
//                    //var treeId = response.responseText;
//
//                    var treeStore = Ext.getCmp('treemenu').store;
//                    var node = treeStore.getNodeById('root');
//
//                    // 存放选择路径
//                    Ext.alarm.moPath = node.getPath();
//
//                    node.expand(true,function(){
//                        var targetNode = Ext.getCmp("treemenu").getStore().getNodeById(treeId);
//                        if (targetNode) {
//                            // 选择默认节点
//                            Ext.getCmp("treemenu").getSelectionModel().select(targetNode, true);
//
//                            // 刷新页面
//                            var treeText = targetNode.data.text;
//                            // 将当前节点id存放
//                            Ext.getCmp('selectTreeNodeId').setValue(treeId);
//
//                            if (treeId) {
//                                var strs = new Array(); //定义一数组
//                                strs = treeId.split("*");
//
//                                // 设置默认选择节点
//                                Ext.getCmp('treeId').setValue(strs[1]);
//                                Ext.getCmp("treemenu").getSelectionModel().select(Ext.getCmp("treemenu").getStore().getNodeById(treeId),true);
//                                // 将节点名称作为顶部标题
//                                var alarmTitle = Ext.getCmp('alarmTitle');
//                                //alarmTitle.setText(Ext.getCmp('treemenu').getRootNode().data.text);
//                                alarmTitle.setText(treeText);
//
//                                // 设置读取数据的请求时间
//                                Ext.getCmp('lastUpdateTime').setValue(Ext.Date.now());
//
//                                // 根据节点id重新加载
//                                // 活动告警
//                                var activeGrid = Ext.getCmp('activeAlarm');
//                                var activeStoreProxy = activeGrid.getStore().getProxy();
//                                //activeStoreProxy.extraParams.treeId = strs[1];
//                                activeStoreProxy.extraParams.treeId = treeObject.path;
//                                activeStoreProxy.extraParams.isNewalarm = Ext.getCmp('isNewalarm_b').getValue();
//                                activeStoreProxy.extraParams.isMyalarm = Ext.getCmp('isMyalarm_b').getValue();
//                                activeStoreProxy.extraParams.lastUpdateTime = '';
//                                activeGrid.getStore().load();
//
//                                Ext.Ajax.request({  
//                                    url:'getMoStatus',  
//                                    params:{  
//                                        //传递参数  
//                                        //treeId: strs[1]
//                                        treeId: treeObject.path
//                                    },  
//                                    success:function(response, options){  
//                                        //Ext.Msg.alert('提示信息','修改成功！');  
//                                        var responseArray = Ext.JSON.decode(response.responseText);
//
//                                        if (responseArray.level0Cnt) {
//                                            if (Ext.alarm.level0 != responseArray.level0Cnt) {
//                                                Ext.getCmp('level0').setText(responseArray.level0Cnt.toString());
//                                                Ext.alarm.level0 = responseArray.level0Cnt.toString();
//
//                                                Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level0Cnt);
//                                            }                                    
//                                        }
//
//                                        if (responseArray.level1Cnt) {
//                                            if (Ext.alarm.level1 != responseArray.level1Cnt) {
//                                                Ext.getCmp('level1').setText(responseArray.level1Cnt.toString());
//                                                Ext.alarm.level1 = responseArray.level1Cnt.toString();
//
//                                                Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level1Cnt);
//                                            }                                    
//                                        }
//
//                                        if (responseArray.level2Cnt) {
//                                            if (Ext.alarm.level2 != responseArray.level2Cnt) {
//                                                Ext.getCmp('level2').setText(responseArray.level2Cnt.toString());
//                                                Ext.alarm.level2 = responseArray.level2Cnt.toString();
//
//                                                Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level2Cnt);
//                                            }                                    
//                                        }
//
//                                        if (responseArray.level3Cnt) {
//                                            if (Ext.alarm.level3 != responseArray.level3Cnt) {
//                                                Ext.getCmp('level3').setText(responseArray.level3Cnt.toString());
//                                                Ext.alarm.level3 = responseArray.level3Cnt.toString();
//
//                                                Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level3Cnt);
//                                            }                                    
//                                        }
//
//                                        if (responseArray.level4Cnt) {
//                                            if (Ext.alarm.level4 != responseArray.level4Cnt) {
//                                                Ext.getCmp('level4').setText(responseArray.level4Cnt.toString());
//                                                Ext.alarm.level4 = responseArray.level4Cnt.toString();
//
//                                                Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level4Cnt);
//                                            }                                    
//                                        }
//
//                                        if (responseArray.myAlarmCnt) {
//                                            if (Ext.alarm.myalarm != responseArray.myAlarmCnt) {
//                                                Ext.getCmp('myalarm').setText('我的告警 ' + responseArray.myAlarmCnt.toString());
//                                                Ext.alarm.myalarm = responseArray.myAlarmCnt.toString();
//                                            }                                    
//                                        }
//
//                                        if (responseArray.newAlarmCnt) {
//                                            if (Ext.alarm.newalarm != responseArray.newAlarmCnt) {
//                                                Ext.getCmp('newalarm').setText('新告警 ' + responseArray.newAlarmCnt.toString());
//                                                Ext.alarm.newalarm = responseArray.newAlarmCnt.toString();
//                                            }                                    
//                                        }
//                                    },
//                                    failure:function(){  
//                                        //Ext.Msg.alert('错误信息','系统错误');  
//                                    }    
//                                });  
//                            }
//                        }
//                    });
//                },
//                failure:function(){  
//                    //Ext.Msg.alert('错误信息','系统错误');  
//                }    
//            });  
//
//        } else {
//            // 从主页直接进入的场合
//            Ext.Ajax.request({
//                url: 'getFirstTreeId',
//                async : false,
//                params:{
//                    id: 'root'
//                },
//                success: function(response, opts) {
//                    /**
//                    var treeInfo = new Array();
//                    treeInfo = response.responseText.split("|||");
//
//                    var treeId = treeInfo[0];
//                    var treeText = treeInfo[1];
//                    */
//                    var treeObject = Ext.JSON.decode(response.responseText);
//
//                    var treeId = treeObject.treeId;
//                    var treeText = treeObject.treeText;
//                    var alarm_count = treeObject.alarm_count;
//
//                    // 将当前节点id存放
//                    Ext.getCmp('selectTreeNodeId').setValue(treeId);
//
//                    var treeStore = Ext.getCmp('treemenu').store;
//                    var node = treeStore.getNodeById('root');
//
//                    node.expand(false,function(){
//                        var strs = new Array(); //定义一数组
//                        strs = treeId.split("*");
//
//                        // 存放选择路径
//                        Ext.alarm.moPath = Ext.getCmp("treemenu").getStore().getNodeById(treeId).getPath();
//
//                        // 设置默认选择节点
//                        Ext.getCmp('treeId').setValue(strs[1]);
//                        Ext.getCmp("treemenu").getSelectionModel().select(Ext.getCmp("treemenu").getStore().getNodeById(treeId),true);
//                        // 将节点名称作为顶部标题
//                        var alarmTitle = Ext.getCmp('alarmTitle');
//                        alarmTitle.setText(Ext.getCmp("treemenu").getStore().getNodeById(treeId).data.text);
//                        //alarmTitle.setText(treeText + ' (' + alarm_count + ')');
//
//                        // 设置读取数据的请求时间
//                        Ext.getCmp('lastUpdateTime').setValue(Ext.Date.now());
//
//                        // 根据节点id重新加载
//                        // 活动告警
//                        var activeGrid = Ext.getCmp('activeAlarm');
//                        var activeStoreProxy = activeGrid.getStore().getProxy();
//                        //activeStoreProxy.extraParams.treeId = strs[1];
//                        activeStoreProxy.extraParams.treeId = treeObject.path;
//                        activeStoreProxy.extraParams.isNewalarm = Ext.getCmp('isNewalarm_b').getValue();
//                        activeStoreProxy.extraParams.isMyalarm = Ext.getCmp('isMyalarm_b').getValue();
//                        activeStoreProxy.extraParams.lastUpdateTime = '';
//                        activeGrid.getStore().load();
//
//                        var treeStore = Ext.getCmp('treemenu').store;
//                        var node = treeStore.getNodeById('root');
//
//                        node.expand(false,function(){
//                            var nodeId = Ext.getCmp('treeId').getValue();
//                            if (nodeId) {
//
//                                Ext.Ajax.request({  
//                                    url:'getMoStatus',  
//                                    params:{  
//                                        //传递参数  
//                                        treeId: nodeId
//                                    },  
//                                    async : false,
//                                    success:function(response, options){  
//                                        //Ext.Msg.alert('提示信息','修改成功！');  
//                                        var responseArray = Ext.JSON.decode(response.responseText);
//
//                                        if (responseArray.level0Cnt) {
//                                            if (Ext.alarm.level0 != responseArray.level0Cnt) {
//                                                Ext.getCmp('level0').setText(responseArray.level0Cnt.toString());
//                                                Ext.alarm.level0 = responseArray.level0Cnt.toString();
//
//                                                Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level0Cnt);
//                                            }                                    
//                                        }
//
//                                        if (responseArray.level1Cnt) {
//                                            if (Ext.alarm.level1 != responseArray.level1Cnt) {
//                                                Ext.getCmp('level1').setText(responseArray.level1Cnt.toString());
//                                                Ext.alarm.level1 = responseArray.level1Cnt.toString();
//
//                                                Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level1Cnt);
//                                            }                                    
//                                        }
//
//                                        if (responseArray.level2Cnt) {
//                                            if (Ext.alarm.level2 != responseArray.level2Cnt) {
//                                                Ext.getCmp('level2').setText(responseArray.level2Cnt.toString());
//                                                Ext.alarm.level2 = responseArray.level2Cnt.toString();
//
//                                                Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level2Cnt);
//                                            }                                    
//                                        }
//
//                                        if (responseArray.level3Cnt) {
//                                            if (Ext.alarm.level3 != responseArray.level3Cnt) {
//                                                Ext.getCmp('level3').setText(responseArray.level3Cnt.toString());
//                                                Ext.alarm.level3 = responseArray.level3Cnt.toString();
//
//                                                Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level3Cnt);
//                                            }                                    
//                                        }
//
//                                        if (responseArray.level4Cnt) {
//                                            if (Ext.alarm.level4 != responseArray.level4Cnt) {
//                                                Ext.getCmp('level4').setText(responseArray.level4Cnt.toString());
//                                                Ext.alarm.level4 = responseArray.level4Cnt.toString();
//
//                                                Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level4Cnt);
//                                            }                                    
//                                        }
//
//                                        if (responseArray.myAlarmCnt) {
//                                            if (Ext.alarm.myalarm != responseArray.myAlarmCnt) {
//                                                Ext.getCmp('myalarm').setText('我的告警 ' + responseArray.myAlarmCnt.toString());
//                                                Ext.alarm.myalarm = responseArray.myAlarmCnt.toString();
//                                            }                                    
//                                        }
//
//                                        if (responseArray.newAlarmCnt) {
//                                            if (Ext.alarm.newalarm != responseArray.newAlarmCnt) {
//                                                Ext.getCmp('newalarm').setText('新告警 ' + responseArray.newAlarmCnt.toString());
//                                                Ext.alarm.newalarm = responseArray.newAlarmCnt.toString();
//                                            }                                    
//                                        }
//                                    },
//                                    failure:function(){  
//                                        //Ext.Msg.alert('错误信息','系统错误');  
//                                    }    
//                                });  
//                            }
//                        });
//                    });
//                },
//                failure: function(response, opts) {
//                    //Ext.Msg.alert('失败','自动刷新GRID not ok');
//                }
//            });   
//
//
//
//        }
//
//    },
//
//    updateTreeNode: function() {
//        // 判断当前页面是否为告警页面
//        if(window.parent.isShow("alarm")){
//            var tree=Ext.getCmp("treemenu");
//
//            if(!tree.getStore().isLoading()){
//
//                var isChanged = false;
//                var currentTotal = 0;
//                // 更新顶部告警图标的数量
//                Ext.Ajax.request({  
//                    url:'getMoStatus',  
//                    params:{  
//                        //传递参数  
//                        treeId:Ext.getCmp('treeId').getValue()
//                    },  
//                    async : false,
//                    success:function(response, options){  
//                        //Ext.Msg.alert('提示信息','修改成功！');  
//                        var responseArray = Ext.JSON.decode(response.responseText);
//
//                        // 将节点名称作为顶部标题
//                        //var alarmTitle = Ext.getCmp('alarmTitle');
//                        //alarmTitle.setText(oLastNode.data.text);
//
//                        if (responseArray.level0Cnt) {
//                            if (Ext.alarm.level0 != responseArray.level0Cnt) {
//                                isChanged = true;
//                            }    
//                            currentTotal = currentTotal + parseInt(responseArray.level0Cnt);
//                        } else if (responseArray.level0Cnt == '0') {
//                            if (Ext.alarm.level0 != responseArray.level0Cnt) {
//                                isChanged = true;
//                            } 
//                        }
//
//                        if (responseArray.level1Cnt) {
//                            if (Ext.alarm.level1 != responseArray.level1Cnt) {    
//                                isChanged = true;
//                            }                       
//                            currentTotal = currentTotal + parseInt(responseArray.level1Cnt);
//                        } else if (responseArray.level1Cnt == '0') {
//                            if (Ext.alarm.level1 != responseArray.level1Cnt) {
//                                isChanged = true;
//                            } 
//                        }            
//
//                        if (responseArray.level2Cnt) {
//                            if (Ext.alarm.level2 != responseArray.level2Cnt) {
//                                isChanged = true;
//                            }             
//                            currentTotal = currentTotal + parseInt(responseArray.level2Cnt);
//                        } else if (responseArray.level2Cnt == '0') {
//                            if (Ext.alarm.level2 != responseArray.level2Cnt) {
//                                isChanged = true;
//                            }
//                        }
//
//                        if (responseArray.level3Cnt) {
//                            if (Ext.alarm.level3 != responseArray.level3Cnt) {
//                                isChanged = true;
//                            } 
//                            currentTotal = currentTotal + parseInt(responseArray.level3Cnt);
//                        } else if (responseArray.level3Cnt == '0') {
//                            if (Ext.alarm.level3 != responseArray.level3Cnt) {
//                                isChanged = true;
//                            }
//                        }
//
//                        if (responseArray.level4Cnt) {
//                            if (Ext.alarm.level4 != responseArray.level4Cnt) {
//                                isChanged = true;
//                            }   
//                            currentTotal = currentTotal + parseInt(responseArray.level4Cnt);
//                        } else if (responseArray.level4Cnt == '0') {
//                            if (Ext.alarm.level4 != responseArray.level4Cnt) {
//                                isChanged = true;
//                            }
//                        }
//                    },
//                    failure:function(){  
//                        //Ext.Msg.alert('错误信息','系统错误');  
//                    }    
//                });  
//
//                // 判断是否有新告警产生
//                if (isChanged) {
//                    if (Ext.alarm.moPath == null || Ext.alarm.moPath == '') {
//                        return;
//                    }
//
//                    // 取得需要更新的节点id列表
//                    Ext.Ajax.request({  
//                        url:'getChangedNode',  
//                        params:{  
//                            //传递参数  
//                            nodePath:Ext.alarm.moPath
//                        },  
//                        async : false,
//                        success:function(response, options){  
//                            var responseArray = Ext.JSON.decode(response.responseText);
//
//                            //alert(responseArray.nodeIds);
//                            var treeStore = Ext.getCmp('treemenu').store;
//
//                            var strs = new Array(); //定义一数组
//                            strs = responseArray.nodeIds.split(",");
//                            for (var moid in strs) {
//                                var targetNode = Ext.getCmp("treemenu").getStore().getNodeById(strs[moid]);
//                                if (targetNode) {
//                                    // 重新组合节点标题
//                                    var oldText = targetNode.data.text;
//                                    var oldTextArr = new Array();
//                                    oldTextArr = oldText.split(" ");
//
//                                    var oldValue = oldTextArr[1].substring(1, oldTextArr[1].length - 1);
//                                    //alert(currentTotal);alert(Ext.alarm.alarmTotal);
//                                    var dValue = currentTotal - Ext.alarm.alarmTotal;
//
//                                    var newAlarmCnt = parseInt(oldValue) + dValue;
//                                    var newText = oldTextArr[0] + " (" + newAlarmCnt + ")";
//                                    // 设置节点标题
//                                    targetNode.set('text', newText);
//
//                                    if (Ext.getCmp('selectTreeNodeId').getValue() == targetNode.data.id) {
//                                        Ext.alarm.alarmTotal = newAlarmCnt;
//                                    }                            
//                                }
//                            }
//                        },
//                        failure:function(){  
//                            //Ext.Msg.alert('错误信息','系统错误');  
//                        }    
//                    });  
//
//                    var treeStore = Ext.getCmp('treemenu').store;
//                    var targetNode = Ext.getCmp("treemenu").getStore().getNodeById(Ext.getCmp('selectTreeNodeId').getValue());
//                    if (targetNode) {
//                        // 选择默认节点
//                        Ext.getCmp("treemenu").getSelectionModel().select(targetNode, true);
//
//                        // 将节点名称作为顶部标题
//                        Ext.getCmp('alarmTitle').setText(targetNode.data.text);
//                    }
//                }      
//            }
//        }
//        /**
//        if(tree.getStore().getRootNode()){
//        tree.getStore().getRootNode().removeAll();
//        }
//        tree.getStore().load({params:{id:"root"}});
//
//        // 存放选择路径
//        var path = Ext.alarm.moPath;
//        tree.expandPath(path, 'id', '/', function(bSuccess, oLastNode){
//            if(!bSuccess) 
//            return;
//
//            //focus 节点，并选中节点！
//            Ext.getCmp("treemenu").getSelectionModel().select(oLastNode, true);
//
//            // 更新顶部告警图标的数量
//            Ext.Ajax.request({  
//                url:'getMoStatus',  
//                params:{  
//                    //传递参数  
//                    treeId:Ext.getCmp('treeId').getValue()
//                },  
//                async : false,
//                success:function(response, options){  
//                    //Ext.Msg.alert('提示信息','修改成功！');  
//                    var responseArray = Ext.JSON.decode(response.responseText);
//
//                    // 将节点名称作为顶部标题
//                    var alarmTitle = Ext.getCmp('alarmTitle');
//                    alarmTitle.setText(oLastNode.data.text);
//
//                    var isChanged = false;
//
//                    if (responseArray.level0Cnt) {
//                        if (Ext.alarm.level0 != responseArray.level0Cnt) {
//                            Ext.getCmp('level0').setText(responseArray.level0Cnt.toString());
//                            Ext.alarm.level0 = responseArray.level0Cnt.toString();
//
//                            isChanged = true;
//                        }                                    
//                    } else if (responseArray.level0Cnt == '0') {
//                        if (Ext.alarm.level0 != responseArray.level0Cnt) {
//                            Ext.getCmp('level0').setText(responseArray.level0Cnt.toString());
//                            Ext.alarm.level0 = responseArray.level0Cnt.toString();
//
//                            isChanged = true;
//                        } 
//                    }
//
//                    if (responseArray.level1Cnt) {
//                        if (Ext.alarm.level1 != responseArray.level1Cnt) {
//                            Ext.getCmp('level1').setText(responseArray.level1Cnt.toString());
//                            Ext.alarm.level1 = responseArray.level1Cnt.toString();
//
//                            isChanged = true;
//                        }                                    
//                    } else if (responseArray.level1Cnt == '0') {
//                        if (Ext.alarm.level1 != responseArray.level1Cnt) {
//                            Ext.getCmp('level1').setText(responseArray.level1Cnt.toString());
//                            Ext.alarm.level1 = responseArray.level1Cnt.toString();
//
//                            isChanged = true;
//                        } 
//                    }            
//
//                    if (responseArray.level2Cnt) {
//                        if (Ext.alarm.level2 != responseArray.level2Cnt) {
//                            Ext.getCmp('level2').setText(responseArray.level2Cnt.toString());
//                            Ext.alarm.level2 = responseArray.level2Cnt.toString();
//
//                            isChanged = true;
//                        }                                    
//                    } else if (responseArray.level2Cnt == '0') {
//                        if (Ext.alarm.level2 != responseArray.level2Cnt) {
//                            Ext.getCmp('level2').setText(responseArray.level2Cnt.toString());
//                            Ext.alarm.level2 = responseArray.level2Cnt.toString();
//
//                            isChanged = true;
//                        }
//                    }
//
//                    if (responseArray.level3Cnt) {
//                        if (Ext.alarm.level3 != responseArray.level3Cnt) {
//                            Ext.getCmp('level3').setText(responseArray.level3Cnt.toString());
//                            Ext.alarm.level3 = responseArray.level3Cnt.toString();
//
//                            isChanged = true;
//                        } 
//                    } else if (responseArray.level3Cnt == '0') {
//                        if (Ext.alarm.level3 != responseArray.level3Cnt) {
//                            Ext.getCmp('level3').setText(responseArray.level3Cnt.toString());
//                            Ext.alarm.level3 = responseArray.level3Cnt.toString();
//
//                            isChanged = true;
//                        }
//                    }
//
//                    if (responseArray.level4Cnt) {
//                        if (Ext.alarm.level4 != responseArray.level4Cnt) {
//                            Ext.getCmp('level4').setText(responseArray.level4Cnt.toString());
//                            Ext.alarm.level4 = responseArray.level4Cnt.toString();
//
//                            isChanged = true;
//                        }                                    
//                    } else if (responseArray.level4Cnt == '0') {
//                        if (Ext.alarm.level4 != responseArray.level4Cnt) {
//                            Ext.getCmp('level4').setText(responseArray.level4Cnt.toString());
//                            Ext.alarm.level4 = responseArray.level4Cnt.toString();
//
//                            isChanged = true;
//                        }
//                    }
//
//                    if (responseArray.myAlarmCnt) {
//                        if (Ext.alarm.myalarm != responseArray.myAlarmCnt) {
//                            Ext.getCmp('myalarm').setText('我的告警 ' + responseArray.myAlarmCnt.toString());
//                            Ext.alarm.myalarm = responseArray.myAlarmCnt.toString();
//
//                            isChanged = true;
//                        }                                    
//                    } else if (responseArray.myAlarmCnt == '0') {
//                        if (Ext.alarm.myalarm != responseArray.myAlarmCnt) {
//                            Ext.getCmp('myalarm').setText('我的告警 ' + responseArray.myAlarmCnt.toString());
//                            Ext.alarm.myalarm = responseArray.myAlarmCnt.toString();
//
//                            isChanged = true;
//                        }  
//                    }
//
//
//                    if (responseArray.newAlarmCnt) {
//                        if (Ext.alarm.newalarm != responseArray.newAlarmCnt) {
//                            Ext.getCmp('newalarm').setText('新告警 ' + responseArray.newAlarmCnt.toString());
//                            Ext.alarm.newalarm = responseArray.newAlarmCnt.toString();
//
//                            isChanged = true;
//                        }                                    
//                    } else if (responseArray.newAlarmCnt == '0') {
//                        if (Ext.alarm.newalarm != responseArray.newAlarmCnt) {
//                            Ext.getCmp('newalarm').setText('新告警 ' + responseArray.newAlarmCnt.toString());
//                            Ext.alarm.newalarm = responseArray.newAlarmCnt.toString();
//
//                            isChanged = true;
//                        } 
//                    }
//                },
//                failure:function(){  
//                    //Ext.Msg.alert('错误信息','系统错误');  
//                }    
//            });  
//        });
//    }
//
//
//
//
//
//    // 遍历树节点历史信息
//    Ext.Ajax.request({
//        url: 'getTreeNodeHistory',
//        params:{  
//            //传递参数  
//            alarmIdList:'',
//            content:'',
//            contentType:''
//        },
//        async : false,
//        success: function(response, opts) {
//            var treeStore = Ext.getCmp('treemenu').store;
//            var treeObject = Ext.JSON.decode(response.responseText);
//            var isRequire = false;
//            Ext.Array.each(treeObject.treeNode, function(record1){
//                Ext.Array.each(treeObject.treeNodeHistory, function(record2){
//                    if (record1.id == record2.id && record1.alarm_count != record2.alarm_count && record1.alarm_count != null) {
//
//                        var node = treeStore.getNodeById(record1.id);
//                        if (node) {
//                            node.set('text', record1.text + ' (' + record1.alarm_count + ')');//设置显示文字
//                            node.set('cls', 'alarm-server');//设置treenode的整体css，这里主要是设置了字体颜色
//
//                            if (record1.id == Ext.getCmp('treeId').getValue()) {
//                                isRequire = true;
//                            }
//                        }
//                    }
//                });
//            });
//
//            if (isRequire) {
//                // 当前页面装载的是当前节点，刷新页面告警数量
//                // 更新顶部告警图标的数量
//                Ext.Ajax.request({  
//                    url:'getMoStatus',  
//                    params:{  
//                        //传递参数  
//                        treeId:Ext.getCmp('treeId').getValue()
//                    },  
//                    async : false,
//                    success:function(response, options){  
//                        //Ext.Msg.alert('提示信息','修改成功！');  
//                        var responseArray = Ext.JSON.decode(response.responseText);
//
//                        var level0 = Ext.getCmp('level0');
//                        if (responseArray.level0Cnt) {
//                            level0.setText(responseArray.level0Cnt.toString());
//                        } else {
//                            level0.setText('0');
//                        }
//                        var level1 = Ext.getCmp('level1');
//                        if (responseArray.level1Cnt) {
//                            level1.setText(responseArray.level1Cnt.toString());
//                        } else {
//                            level1.setText('0');
//                        }
//                        var level2 = Ext.getCmp('level2');
//                        if (responseArray.level2Cnt) {
//                            level2.setText(responseArray.level2Cnt.toString());
//                        } else {
//                            level2.setText('0');
//                        }
//                        var level3 = Ext.getCmp('level3');
//                        if (responseArray.level3Cnt) {
//                            level3.setText(responseArray.level3Cnt.toString());
//                        } else {
//                            level3.setText('0');
//                        }
//                        var level4 = Ext.getCmp('level4');
//                        if (responseArray.level4Cnt) {
//                            level4.setText(responseArray.level4Cnt.toString());
//                        } else {
//                            level4.setText('0');
//                        }
//                        var myalarm = Ext.getCmp('myalarm');
//                        if (responseArray.myAlarmCnt) {
//                            myalarm.setText('我的告警 ' + responseArray.myAlarmCnt.toString());
//                        } else {
//                            myalarm.setText('我的告警 0');
//                        }
//                        var newalarm = Ext.getCmp('newalarm');
//                        if (responseArray.newAlarmCnt) {
//                            newalarm.setText('新告警 ' + responseArray.newAlarmCnt.toString());
//                        } else {
//                            newalarm.setText('新告警 0');
//                        }
//                    },
//                    failure:function(){  
//                        //Ext.Msg.alert('错误信息','系统错误');  
//                    }    
//                });  
//            }
//        },
//        failure: function(response, opts) {
//            //Ext.Msg.alert('失败','自动刷新菜单not ok');
//        }
//    });
//
//    }    */
//
//
//
//    },
//
//    updateGridData: function() {
//        // 判断当前页面是否为告警页面
//        if(window.parent.isShow("alarm")){
//
//            Ext.alarm.alarmTotal = 0;
//
//            Ext.lastUpdateTime = Ext.getCmp('lastUpdateTime').getValue();
//            // 重新设置最后请求时间
//            Ext.getCmp('lastUpdateTime').setValue(Ext.Date.now());
//            //alert(Ext.util.Format.date(new Date(), 'Y-m-d H:m:s'));
//
//            // 将活动告警的复选记录行保存在隐藏值中
//            var alarmGird = Ext.getCmp('activeAlarm');
//            var gridRecord = alarmGird.getSelectionModel().getSelection();
//            var ids = "";
//            if(gridRecord.length != 0){
//                for(var i = 0; i < gridRecord.length; i++){
//                    ids += gridRecord[i].get("id");
//                    if(i < gridRecord.length-1){
//                        ids = ids + ",";
//                    }
//                }
//
//                Ext.getCmp('selectIds').setValue(ids);
//            }
//
//            // 刷新活动告警
//            Ext.Ajax.request({
//                url: 'getActiveAlarmData',
//                params:{  
//                    //传递参数  
//                    treeId: Ext.getCmp('treeId').getValue(),
//                    level: Ext.getCmp('levelStr').getValue(),
//                    content:'',
//                    contentType:'',
//                    lastUpdateTime:Ext.lastUpdateTime,
//                    isNewalarm:Ext.getCmp('isNewalarm_b').getValue(),
//                    isMyalarm:Ext.getCmp('isMyalarm_b').getValue()
//                },
//                async : false,
//                success: function(response, opts) {
//                    var gridData = Ext.JSON.decode(response.responseText);
//                    //获取ext组件并getStore()调用loadData方法加载对应数据
//                    var alarmGird = Ext.getCmp('activeAlarm');
//                    var isRequire = false;
//                    if (gridData.activeTotal > 0 ) {
//
//                        for (var record in gridData.activeData) {
//                            var row = alarmGird.getStore().getById(gridData.activeData[record].id);
//                            if (row) {
//                                row.set(record); 
//                            } else {
//                                isRequire = true;
//                                Ext.getCmp('activeAlarm').getStore().insert(0, gridData.activeData[record]);
//                            }
//                        }
//
//                        if (isRequire) {
//                            // 当前页面告警数量有变化时
//                            // 更新顶部告警图标的数量
//                            Ext.Ajax.request({  
//                                url:'getMoStatus',  
//                                params:{  
//                                    //传递参数  
//                                    treeId:Ext.getCmp('treeId').getValue()
//                                },  
//                                async : false,
//                                success:function(response, options){  
//                                    //Ext.Msg.alert('提示信息','修改成功！');  
//                                    var responseArray = Ext.JSON.decode(response.responseText);
//
//                                    if (responseArray.level0Cnt) {
//                                        if (Ext.alarm.level0 != responseArray.level0Cnt) {
//                                            Ext.getCmp('level0').setText(responseArray.level0Cnt.toString());
//                                            Ext.alarm.level0 = responseArray.level0Cnt.toString();
//
//                                            Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level0Cnt);
//                                        }                                    
//                                    } else if (responseArray.level0Cnt == '0') {
//                                        if (Ext.alarm.level0 != responseArray.level0Cnt) {
//                                            Ext.getCmp('level0').setText(responseArray.level0Cnt.toString());
//                                            Ext.alarm.level0 = responseArray.level0Cnt.toString();
//
//                                            Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level0Cnt);
//                                        } 
//                                    }
//
//                                    if (responseArray.level1Cnt) {
//                                        if (Ext.alarm.level1 != responseArray.level1Cnt) {
//                                            Ext.getCmp('level1').setText(responseArray.level1Cnt.toString());
//                                            Ext.alarm.level1 = responseArray.level1Cnt.toString();
//
//                                            Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level1Cnt);
//                                        }                                    
//                                    } else if (responseArray.level1Cnt == '0') {
//                                        if (Ext.alarm.level1 != responseArray.level1Cnt) {
//                                            Ext.getCmp('level1').setText(responseArray.level1Cnt.toString());
//                                            Ext.alarm.level1 = responseArray.level1Cnt.toString();
//
//                                            Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level1Cnt);
//                                        } 
//                                    }            
//
//                                    if (responseArray.level2Cnt) {
//                                        if (Ext.alarm.level2 != responseArray.level2Cnt) {
//                                            Ext.getCmp('level2').setText(responseArray.level2Cnt.toString());
//                                            Ext.alarm.level2 = responseArray.level2Cnt.toString();
//
//                                            Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level2Cnt);
//                                        }                                    
//                                    } else if (responseArray.level2Cnt == '0') {
//                                        if (Ext.alarm.level2 != responseArray.level2Cnt) {
//                                            Ext.getCmp('level2').setText(responseArray.level2Cnt.toString());
//                                            Ext.alarm.level2 = responseArray.level2Cnt.toString();
//
//                                            Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level2Cnt);
//                                        }
//                                    }
//
//                                    if (responseArray.level3Cnt) {
//                                        if (Ext.alarm.level3 != responseArray.level3Cnt) {
//                                            Ext.getCmp('level3').setText(responseArray.level3Cnt.toString());
//                                            Ext.alarm.level3 = responseArray.level3Cnt.toString();
//
//                                            Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level3Cnt);
//                                        } 
//                                    } else if (responseArray.level3Cnt == '0') {
//                                        if (Ext.alarm.level3 != responseArray.level3Cnt) {
//                                            Ext.getCmp('level3').setText(responseArray.level3Cnt.toString());
//                                            Ext.alarm.level3 = responseArray.level3Cnt.toString();
//
//                                            Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level3Cnt);
//                                        }
//                                    }
//
//                                    if (responseArray.level4Cnt) {
//                                        if (Ext.alarm.level4 != responseArray.level4Cnt) {
//                                            Ext.getCmp('level4').setText(responseArray.level4Cnt.toString());
//                                            Ext.alarm.level4 = responseArray.level4Cnt.toString();
//
//                                            Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level4Cnt);
//                                        }                                    
//                                    } else if (responseArray.level4Cnt == '0') {
//                                        if (Ext.alarm.level4 != responseArray.level4Cnt) {
//                                            Ext.getCmp('level4').setText(responseArray.level4Cnt.toString());
//                                            Ext.alarm.level4 = responseArray.level4Cnt.toString();
//
//                                            Ext.alarm.alarmTotal = Ext.alarm.alarmTotal + parseInt(responseArray.level4Cnt);
//                                        }
//                                    }
//
//                                    if (responseArray.myAlarmCnt) {
//                                        if (Ext.alarm.myalarm != responseArray.myAlarmCnt) {
//                                            Ext.getCmp('myalarm').setText('我的告警 ' + responseArray.myAlarmCnt.toString());
//                                            Ext.alarm.myalarm = responseArray.myAlarmCnt.toString();
//                                        }                                    
//                                    } else if (responseArray.myAlarmCnt == '0') {
//                                        if (Ext.alarm.myalarm != responseArray.myAlarmCnt) {
//                                            Ext.getCmp('myalarm').setText('我的告警 ' + responseArray.myAlarmCnt.toString());
//                                            Ext.alarm.myalarm = responseArray.myAlarmCnt.toString();
//                                        }  
//                                    }
//
//                                    if (responseArray.newAlarmCnt) {
//                                        if (Ext.alarm.newalarm != responseArray.newAlarmCnt) {
//                                            Ext.getCmp('newalarm').setText('新告警 ' + responseArray.newAlarmCnt.toString());
//                                            Ext.alarm.newalarm = responseArray.newAlarmCnt.toString();
//                                        }                                    
//                                    } else if (responseArray.newAlarmCnt == '0') {
//                                        if (Ext.alarm.newalarm != responseArray.newAlarmCnt) {
//                                            Ext.getCmp('newalarm').setText('新告警 ' + responseArray.newAlarmCnt.toString());
//                                            Ext.alarm.newalarm = responseArray.newAlarmCnt.toString();
//                                        } 
//                                    }
//                                },
//                                failure:function(){  
//                                    //Ext.Msg.alert('错误信息','系统错误');  
//                                }    
//                            });
//
//                            // 更新树节点告警数量
//
//                        }
//                    }
//                },
//                failure: function(response, opts) {
//                    //Ext.Msg.alert('失败','自动刷新GRID not ok');
//                }
//            });
//        }


    }

});
