/*
 * File: app/model/KpiValue.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.model.KpiValue', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'MO_ID'
        },
        {
            name: 'MO_NAME'
        },
        {
            name: 'AMP_INSTANCE_ID'
        },
        {
            name: 'AMP_INSTANCE_NAME'
        },
        {
            name: 'KPI_CODE'
        },
        {
            name: 'KPI_NAME'
        },
        {
            convert: function(v, rec) {
                if(v==null || v==""){
                    return null;
                }
                else{
                    return new Date(v);
                }

            },
            name: 'LAST_UPDATE_TIME',
            type: 'date'
        },
        {
            name: 'VALUE'
        },
        {
            name: 'INSTANCE'
        },
        {
            name: 'STATUS'
        },
        {
            name: 'alarmId'
        },
        {
            name: 'THRESHOLD_LEVEL'
        },
        {
            name: 'THRESHOLD'
        },
        {
            name: 'STR_VALUE'
        },
        {
            name: 'VALUE_DESC'
        },
        {
            name: 'ITEM_COUNT'
        },
        {
            name: 'HAS_CHILDREN'
        }
    ]
});