/*
 * File: app/model/KpiValue.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.model.KpiValuez', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'cpuzyl'
        },
        {
            name: 'jcyxid'
        },
        {
            name: 'jcyxml'
        },
        {
            name: 'jcncsyl'
        },
        {
            name: 'jcyxsj'
        },
        {
            name: 'jcssyh'
        },
        {
            name: 'jczt'
        },
        
        {
        	name: 'instance'
        },
        
        {
        	name: 'added'
        },
        
        {
            name: '1001014002'
        },
        {
            name: '1001014003'
        },
        {
            name: '1001014004'
        },
        {
            name: '1001014001'
        },
        
        
        
        {
            name: '1001018001'
        },
        {
            name: '1001018003'
        },
        {
            name: '1001018002'
        },        
        
        
        {
            name: '1001019002'
        },
        {
            name: '1001019003'
        },
        {
            name: '1001019001'
        },
        
        
        {
            name: '1001003002'
        },
        {
            name: '1001003003'
        },
        {
            name: '1001003001'
        },
        {
            name: '1001003004'
        }
        /////////////////////////////
        ,
        {
        	name: '1002001013'
        }
        ,
        {
        	name: '1002001018'
        }
        ,
        {
        	name: '1002001012'
        }
        ,
        {
        	name: '1002001009'
        }
        ,
        {
        	name: '1002001008'
        }
        ,
        {
        	name: '1002001017'
        }
        ,
        {
        	name: '1002001015'
        }
        ,
        {
        	name: '1002001007'
        }
        ,
        {
        	name: '1002001025'
        }
        ,
        {
        	name: '1002001003'
        }
        ,
        {
        	name: '1002001020'
        }
        ,
        {
        	name: '1002001001'
        }
        ,
        {
        	name: '1002001019'
        }
        ,
        {
        	name: '1002001004'
        }
        ///////////
//        ,
//        {
//            name: 'HAS_CHILDREN'
//        }
        
        ,
        {
            name: '1001022001'
        },
        {
            name: '1001032001'
        },
        {
            name: '1001004001'
        },
        {
            name: '1001004002'
        },
        {
            name: '1001004003'
        },
        {
            name: '1001004005'
        },
        {
            name: '1001005001'
        },
        
        {
        	name: '1001010001'
        },
        
        {
        	name: '1001010002'
        },
        
        {
            name: '1001010003'
        },
        {
            name: '1001010005'
        },
        {
            name: '1001011004'
        },
        {
            name: '1001011002'
        },
        
        
        
        {
            name: '1001011003'
        },
        {
            name: '1001011001'
        },
        {
            name: '1001011005'
        },        
        
        
        {
            name: '1001012001'
        },
        {
            name: '1001013004'
        },
        {
            name: '1001013002'
        },
        
        
        {
            name: '1001013001'
        },
        {
            name: '1001013003'
        },
        {
            name: '1001015003'
        },
        {
            name: '1001015002'
        }
        /////////////////////////////
        ,
        {
        	name: '1001021004'
        }
        ,
        {
        	name: '1001021005'
        }
        ,
        {
        	name: '1001021008'
        }
        ,
        {
        	name: '1001021001'
        }
        ,
        {
        	name: '1001021009'
        }
        ,
        {
        	name: '1001021002'
        }
        
    ]
});