/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'queryPanel',
                    layout: {
                        type: 'fit'
                    },
                    suspendLayout: false,
                    bodyBorder: false,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            id: 'queryBar',
                            itemId: 'queryBar',
                            autoScroll: false
                        }
                    ],
                    items: [
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            layout: {
                                type: 'fit'
                            },
                            bodyBorder: false,
                            title: '',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    hidden: true,
                                    items: [
                                        {
                                            xtype: 'button',
                                            icon: '../source/image/exportPdf.png',
                                            text: avmon.ireport.exportPDF,
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            icon: '../source/image/word.gif',
                                            text: avmon.ireport.exportWord,
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick1,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            icon: '../source/image/excel.gif',
                                            text: avmon.ireport.exportExcel,
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick2,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {
        if(Ext.ireportCommon.reportId != '' && Ext.ireportCommon.reportId != null){
            var toolBar = button.up("toolbar").up("panel").up("panel").down("toolbar");
            //验证过滤参数(不能为空)
            var flag = false;
            var params = [];
            
            
            
            Ext.Array.forEach(toolBar.items.items, function(item, index, allItems) { 
                //alert(item.rawValue);
            	
            	if(item.name=="parameter"){
                    if((item.rawValue=='' || item.rawValue==null)&&item.id!="SUBREPORT_DIR|java.lang.String"){
                        flag = true;			    		
                    }
                    if(item.id.indexOf("customTime|")>-1){
                    	if(item.id.indexOf("customTime|date")>-1){
                    		params.push(item.id.substring(16)+"|"+item.rawValue+" "+item.next().rawValue+":00");
                    	}
                    }else{
                    	params.push(item.id+"|"+item.rawValue);
                    }
                }else if(item.name=="_reportType"){
                	params.push("_reportType|"+item.value);
                }
            }); 
//            if(flag){
//                alert(avmon.ireport.parameterValueCantBeEmpty);
//            }else{
                //导出
                var url  = "../source/config/report-html.jsp?reportId="+Ext.ireportCommon.reportId
                +"&type=pdf&params="+encodeURI(params.join(";"));
                window.location=url;  	    			
//            } 
        }
    },

    onButtonClick1: function(button, e, options) {
        if(Ext.ireportCommon.reportId != '' && Ext.ireportCommon.reportId != null){
            var toolBar = button.up("toolbar").up("panel").up("panel").down("toolbar");
            //验证过滤参数(不能为空)
            var flag = false;
            var params = [];
            Ext.Array.forEach(toolBar.items.items, function(item, index, allItems) { 
                //alert(item.rawValue);
            	if(item.name=="parameter"){
                    if((item.rawValue=='' || item.rawValue==null)&&item.id!="SUBREPORT_DIR|java.lang.String"){
                        flag = true;			    		
                    }
                    if(item.id.indexOf("customTime|")>-1){
                    	if(item.id.indexOf("customTime|date")>-1){
                    		params.push(item.id.substring(16)+"|"+item.rawValue+" "+item.next().rawValue+":00");
                    	}
                    }else{
                    	params.push(item.id+"|"+item.rawValue);
                    }
                }else if(item.name=="_reportType"){
                	params.push("_reportType|"+item.value);
                }
            }); 
//            if(flag){
//                alert(avmon.ireport.parameterValueCantBeEmpty);
//            }else{
                //导出
                var url  = "../source/config/report-html.jsp?reportId="+Ext.ireportCommon.reportId
                +"&type=word&params="+encodeURI(params.join(";"));
                window.location=url;  	    			
//            } 
        }
    },

    onButtonClick2: function(button, e, options) {
        if(Ext.ireportCommon.reportId != '' && Ext.ireportCommon.reportId != null){
            var toolBar = button.up("toolbar").up("panel").up("panel").down("toolbar");
            //验证过滤参数(不能为空)
            var flag = false;
            var params = [];
            Ext.Array.forEach(toolBar.items.items, function(item, index, allItems) { 
                //alert(item.rawValue);
            	if(item.name=="parameter"){
                    if((item.rawValue=='' || item.rawValue==null)&&item.id!="SUBREPORT_DIR|java.lang.String"){
                        flag = true;			    		
                    }
                    if(item.id.indexOf("customTime|")>-1){
                    	if(item.id.indexOf("customTime|date")>-1){
                    		params.push(item.id.substring(16)+"|"+item.rawValue+" "+item.next().rawValue+":00");
                    	}
                    }else{
                    	params.push(item.id+"|"+item.rawValue);
                    }
                }else if(item.name=="_reportType"){
                	params.push("_reportType|"+item.value);
                }
				
            }); 
//            if(flag){
//                alert(avmon.ireport.parameterValueCantBeEmpty);
//            }else{
                //导出
                var url  = "../source/config/report-html.jsp?reportId="+Ext.ireportCommon.reportId
                +"&type=excel&params="+encodeURI(params.join(";"));
                window.location=url;  	    			
//            } 
        }
    }

});