/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    onViewportAfterRender: function(abstractcomponent, options) {
        var toolBar = abstractcomponent.down("panel").down("toolbar");

        function loadReportHtml(){
        	
        	Array.prototype.in_array = function(e)  
			{  
			for(i=0;i<this.length && this[i]!=e;i++);  
			return !(i==this.length);  
			}  

        	
        	
            var progressBar=Ext.Msg.wait("",avmon.common.reminder,{text:avmon.ireport.loading});
            var flag = false;
            var params = [];

            var customParams = [];
            Ext.Array.forEach(toolBar.items.items, function(item, index, allItems) { 
                //alert(item.rawValue);
                if(item.name=="parameter"){
                    if((item.rawValue=='' || item.rawValue==null)&&item.id!="SUBREPORT_DIR|java.lang.String"){
                        flag = true;			    		
                    }
                    if(item.id.indexOf("customTime|")>-1){
                    	if(item.id.indexOf("customTime|date")>-1){
                    		params.push(item.id.substring(16)+"|"+item.rawValue+" "+item.next().rawValue+":00");
                    	}
                    }else{
                    	params.push(item.id+"|"+item.rawValue);
                    }
                }else if(item.name=="_reportType"){
                	params.push("_reportType|"+item.value);
                }
            }); 
            
//            if(flag){
//                alert("参数值不能为空!");
//            }else{
                //展示报表
                //alert(Ext.ireportCommon.reportId);
                $.ajax({
                    type: "POST",
                    url: "../source/config/report-html.jsp",
                    data: "reportId="+Ext.ireportCommon.reportId+"&type=html&params="+params.join(";"),
                    contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                    success: function(data){
                        data = data.replace(new RegExp('font-size: 10px', 'g'), 'font-size: 14px');
                        abstractcomponent.down("panel").down("panel").update(data);

                        var buttonBar = abstractcomponent.down("panel").down("panel").down("toolbar");
                        buttonBar.show();
                        progressBar.hide();

                    }
                });		    			
//            } 
        }


        if(list.length > 0){
        	if(list[0].NAME=='FromDate'||list[0].NAME=='ToDate'){
        		for(var i=0; i<list.length; i++){
        			if(list[i].NAME=='FromDate'||list[i].NAME=='ToDate'||list[i].NAME=='ReportType'||list[i].NAME=='KPI_CODE'){continue;}
	                var tdName = list[i].NAME;
	                if(tdName=="startTime"){
	                    tdName = avmon.ireport.startTime;
	                }else if(tdName=="endTime"){
	                    tdName = avmon.ireport.dueTime;
	                }else if(tdName=="reportDate"){
	                    tdName = avmon.ireport.inspectionDate;
	                }else if(tdName=="AlarmTitle"){
	                    tdName = avmon.alarm.alarmTitle;
	                }
	
	
	                if(list[i].TYPE.indexOf("Date") != -1){
	                    //set value
	                    toolBar.add({
	                        xtype: 'textfield',
	                        name:'parameter',
	                        width:190,
	                        labelWidth:58,
	                        id:list[i].NAME+"|"+list[i].TYPE,               
	                        fieldLabel: tdName
	                    })
	
	                }else if(list[i].TYPE.indexOf("Time") != -1){
	                    //set value
	                    if(tdName==avmon.ireport.startTime){
	                    	toolBar.add({
	                            xtype: 'datefield',
								name:'parameter',
	                            width: 140,
	                            fieldLabel: avmon.ireport.time,
	                            labelWidth: 40,
	                            format: 'Y-m-d',
	                            id:"customTime|date|"+list[i].NAME+"|"+list[i].TYPE,
	                            value:Ext.Date.format(new Date(), "Y-m-d")
	                        },
	                        {
	                            xtype: 'timefield',
	                            name:'parameter',
	                            width: 58,
	                            value: '00:00',
	                            fieldLabel: '',
	                            editable: true,
	                            format: 'H:i',
	                            id:"customTime|time|"+list[i].NAME+"|"+list[i].TYPE,
	                            increment: 60
	                        });    
	                    }else if(tdName==avmon.ireport.dueTime){
	                    	toolBar.add({
	                            xtype: 'datefield',
								name:'parameter',
	                            width: 140,
	                            fieldLabel: avmon.ireport.time,
	                            labelWidth: 40,
	                            format: 'Y-m-d',
	                            id:"customTime|date|"+list[i].NAME+"|"+list[i].TYPE,
	                            value:Ext.Date.format(new Date(), "Y-m-d")
	                        },
	                        {
	                            xtype: 'timefield',
	                            name:'parameter',
	                            width: 58,
	                            value: '23:00',
	                            fieldLabel: '',
	                            editable: true,
	                            format: 'H:i',
	                            id:"customTime|time|"+list[i].NAME+"|"+list[i].TYPE,
	                            increment: 60
	                        });
	                    }else{
	                        toolBar.add({
	                            xtype: 'textfield',
	                            name:'parameter',
	                            width:190,
	                            labelWidth:58,
	                            id:list[i].NAME+"|"+list[i].TYPE,
	                            value:Ext.Date.format(new Date(), "Y-m-d H:i:s"),
	                            fieldLabel: tdName
	                        });
	                    }
	                }else{
	                    if(list[i].NAME=="SUBREPORT_DIR"){
	
	                        toolBar.add({
	                            xtype: 'textfield',
	                            name:'parameter',
	                            hidden:true,
	                            id:list[i].NAME+"|"+list[i].TYPE,
	                            value:list[i].DEFAULT,
	                            fieldLabel: tdName
	                        });
	
	                    }else if(list[i].NAME=="reportDate"){
	                        toolBar.add({
	                            xtype: 'datefield',
	                            name:'parameter',
	                            width: 160,
	                            fieldLabel: avmon.ireport.time,
	                            labelWidth: 60,
	                            format: 'Y-m-d',
	                            value:Ext.Date.format(new Date(), "Y-m-d"),
	                            id:list[i].NAME+"|"+list[i].TYPE,
	                            fieldLabel: tdName
	                        });
	                    }else{
	                        toolBar.add({
	                            xtype: 'textfield',
	                            name:'parameter',
	                            width:190,
	                            labelWidth:58,
	                            id:list[i].NAME+"|"+list[i].TYPE,
	                            value:list[i].DEFAULT,
	                            fieldLabel: tdName
	                        });
	                    }
	                }
	            }
        		
        		 //增加月  
        	    function addMonths(date, value) {
        	        date.setMonth(date.getMonth() + value);
        	        return date;
        	    }
        	    
        	    function addDays(date, value){
        	    	date.setDate(date.getDate() + value);
         	        return date;
        	    }
        	    
        		var tempDate = new Date();
        		var tempDate2 ;
        		var maxDate = new Date(); 
        		var defalutReportType;
        		var temp = [{'value' : 0,'display' : avmon.ireport.dailyReport}, {'value' : 1,'display' : avmon.ireport.weeklyReport}, {'value' : 2,'display' : avmon.ireport.monthlyReport}];
        		if(Ext.ireportCommon.reportId=='PerformanceAll'||Ext.ireportCommon.reportId=='PerformanceCPUByApp'||Ext.ireportCommon.reportId=='PerformanceCPUByHost'||Ext.ireportCommon.reportId=='PerformanceMemByApp'||Ext.ireportCommon.reportId=='PerformanceMemByHost'){
        			temp = [{'value' : 2,'display' : avmon.ireport.monthlyReport}];
        			tempDate2 = addMonths(tempDate,-1);
        			defalutReportType = 2;
        			
        			var dt = new Date();  
        		    dt.setDate(1);  
        		    dt.setMonth(dt.getMonth());  
        		    cdt = new Date(dt.getTime()-1000*60*60*24);  
        			maxDate = cdt;
        			tempDate2 = cdt;
        		}else{
        			tempDate2 = addDays(tempDate,-1);
        			defalutReportType = 0;
        		}
        		
        		var data = eval(temp);
        		
        		toolBar.add({
			        fieldLabel: avmon.ireport.reportType,
			        name: '_reportType',
			        allowBlank: false,
			        xtype : 'combobox',
					store : Ext.create('Ext.data.Store', {
								fields : ['value', 'display'],
								data : data
							}),
					queryMode : 'local',
					editable : false,
					value:defalutReportType,
					valueField : 'value',
					displayField : 'display'
			    },{
                    xtype: 'tbseparator'
                },{
                    xtype: 'datefield',
                    name:'parameter',
                    width: 200,
                    fieldLabel: avmon.ireport.dateSelect,
                    labelWidth: 100,
                    format: 'Y-m-d',
                    value:tempDate2,
                    maxValue:maxDate,
                    id:"commonReportDate|Date"
                },{
                    xtype: 'tbseparator'
                },{
                    text: avmon.ireport.generateReport,
                    icon: '../source/image/export.gif',
                    handler: function () { 
                        loadReportHtml(); 
                    } 

                });
                toolBar.doLayout();
        	}else{
	        	for(var i=0; i<list.length; i++){
	
	                var tdName = list[i].NAME;
	                if(tdName=="startTime"){
	                    tdName = avmon.ireport.startTime;
	                }else if(tdName=="endTime"){
	                    tdName = avmon.ireport.dueTime;
	                }else if(tdName=="reportDate"){
	                    tdName = avmon.ireport.inspectionDate;
	                }
	
	
	                if(list[i].TYPE.indexOf("Date") != -1){
	                    //set value
	                    toolBar.add({
	                        xtype: 'textfield',
	                        name:'parameter',
	                        width:190,
	                        labelWidth:58,
	                        id:list[i].NAME+"|"+list[i].TYPE,               
	                        fieldLabel: tdName
	                    })
	
	                }else if(list[i].TYPE.indexOf("Time") != -1){
	                    //set value
	                    if(tdName==avmon.ireport.startTime){
	                    	toolBar.add({
	                            xtype: 'datefield',
								name:'parameter',
	                            width: 140,
	                            fieldLabel: avmon.ireport.time,
	                            labelWidth: 40,
	                            format: 'Y-m-d',
	                            id:"customTime|date|"+list[i].NAME+"|"+list[i].TYPE,
	                            value:Ext.Date.format(new Date(), "Y-m-d")
	                        },
	                        {
	                            xtype: 'timefield',
	                            name:'parameter',
	                            width: 58,
	                            value: '00:00',
	                            fieldLabel: '',
	                            editable: true,
	                            format: 'H:i',
	                            id:"customTime|time|"+list[i].NAME+"|"+list[i].TYPE,
	                            increment: 60
	                        });    
	                    }else if(tdName==avmon.ireport.dueTime){
	                    	toolBar.add({
	                            xtype: 'datefield',
								name:'parameter',
	                            width: 140,
	                            fieldLabel: avmon.ireport.time,
	                            labelWidth: 40,
	                            format: 'Y-m-d',
	                            id:"customTime|date|"+list[i].NAME+"|"+list[i].TYPE,
	                            value:Ext.Date.format(new Date(), "Y-m-d")
	                        },
	                        {
	                            xtype: 'timefield',
	                            name:'parameter',
	                            width: 58,
	                            value: '23:00',
	                            fieldLabel: '',
	                            editable: true,
	                            format: 'H:i',
	                            id:"customTime|time|"+list[i].NAME+"|"+list[i].TYPE,
	                            increment: 60
	                        });
	                    }else{
	                        toolBar.add({
	                            xtype: 'textfield',
	                            name:'parameter',
	                            width:190,
	                            labelWidth:58,
	                            id:list[i].NAME+"|"+list[i].TYPE,
	                            value:Ext.Date.format(new Date(), "Y-m-d H:i:s"),
	                            fieldLabel: tdName
	                        });
	                    }
	                }else{
	                    if(list[i].NAME=="SUBREPORT_DIR"){
	
	                        toolBar.add({
	                            xtype: 'textfield',
	                            name:'parameter',
	                            hidden:true,
	                            id:list[i].NAME+"|"+list[i].TYPE,
	                            value:list[i].DEFAULT,
	                            fieldLabel: tdName
	                        });
	
	                    }else if(list[i].NAME=="reportDate"){
	                        toolBar.add({
	                            xtype: 'datefield',
	                            name:'parameter',
	                            width: 160,
	                            fieldLabel: avmon.ireport.time,
	                            labelWidth: 60,
	                            format: 'Y-m-d',
	                            value:Ext.Date.format(new Date(), "Y-m-d"),
	                            id:list[i].NAME+"|"+list[i].TYPE,
	                            fieldLabel: tdName
	                        });
	                    }else{
	                        toolBar.add({
	                            xtype: 'textfield',
	                            name:'parameter',
	                            width:190,
	                            labelWidth:58,
	                            id:list[i].NAME+"|"+list[i].TYPE,
	                            value:list[i].DEFAULT,
	                            fieldLabel: tdName
	                        });
	                    }
	                }
	
	                if(i == list.length-1){
	                    //添加查询按钮
	                    toolBar.add({
	                        xtype: 'tbseparator'
	                    },{
	                        text: avmon.ireport.generateReport,
	                        icon: '../source/image/export.gif',
	                        handler: function () { 
	                            loadReportHtml(); 
	                        } 
	
	                    });
	
	                    //var queryBtn = $("<input type='button' value=avmon.ireport.generateReport name='query_btn' id='query_btn' onclick='loadReportHtml()' />");
	
	                }
	
	                toolBar.doLayout();
	            }
        	}
        	// loadReportHtml();
        }
        //else{
            loadReportHtml();
        //}
    },

    init: function(application) {
        this.control({
            "viewport": {
                afterrender: this.onViewportAfterRender
            }
        });
    }

});
