/*
 * File: app/view/VirtualListViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('vmList.view.VirtualListViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    id: 'vmListTabs',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            id: 'physicalMachinePanel',
                            layout: {
                                type: 'fit'
                            },
                            title: avmon.vmlist.physicsHost,
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id:'physicalMachineGrid',
                                    store: 'PhysicalMachineStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: avmon.vmlist.physicsHostName
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'powerStatus',
                                            text: avmon.vmlist.status
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'vmlist',
                                            text: avmon.vmlist.vmlist
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'cpu',
                                            text: avmon.vmlist.cpusage+'(%)'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'memPer',
                                            text: avmon.vmlist.memusage +'(%)'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'mem',
                                            text: avmon.vmlist.memSize+'(MB)'
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store: 'PhysicalMachineStore'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'virtualMachinePanel',
                            itemId: 'virtualMachinePanel',
                            layout: {
                                type: 'fit'
                            },
                            title: avmon.dashboard.vmhost,
                            tabConfig: {
                                xtype: 'tab',
                                listeners: {
                                    click: {
                                        fn: me.onTabClick,
                                        scope: me
                                    }
                                }
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    autoRender: true,
                                    id: 'vmGrid',
                                    itemId: 'vmGrid',
                                    store: 'VirtualMachineStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: avmon.vmlist.vmName
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'status',
                                            text: avmon.vmlist.status
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'host',
                                            text: avmon.vmlist.host
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'usedSpace',
                                            text: avmon.vmlist.usedSpace
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'hostFre',
                                            text: avmon.vmlist.hostFre+'(MHz)'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'hostMem',
                                            text: avmon.vmlist.hostMem+'(MB)'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'clientMemUsage',
                                            text: avmon.vmlist.cpusage+'-%'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'mem',
                                            text: avmon.vmlist.memSize
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'uuid',
                                            hidden:true,
                                            text: 'UUID'
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store: 'VirtualMachineStore'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'storagePanel',
                            layout: {
                                type: 'fit'
                            },
                            title: avmon.vmlist.storage,
                            tabConfig: {
                                xtype: 'tab',
                                listeners: {
                                    click: {
                                        fn: me.onTabClick1,
                                        scope: me
                                    }
                                }
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'storageGrid',
                                    itemId: 'storageGrid',
                                    store: 'StorageStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: avmon.vmlist.storageNm
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'vmlist',
                                            text: '设备'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'diskType',
                                            text: '驱动器类型'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'size',
                                            text: '容量'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'freeSpace',
                                            text: '可用空间'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'type',
                                            text: '类型'
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store: 'StorageStore'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onTabClick: function(button, e, eOpts) {
        Ext.getCmp('vmGrid').store.load();
    },

    onTabClick1: function(button, e, eOpts) {
        Ext.getCmp('storageGrid').store.load();
    }

});