/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    frame: true,
                    layout: {
                        type: 'absolute'
                    },
                    title: '小工具',
                    items: [
                        {
                            xtype: 'textareafield',
                            x: 30,
                            y: 20,
                            height: 92,
                            itemId: 'regText',
                            width: 780,
                            fieldLabel: '正则表达式',
                            name: 'regText'
                        },
                        {
                            xtype: 'textareafield',
                            x: 30,
                            y: 140,
                            height: 92,
                            itemId: 'targetText',
                            width: 780,
                            fieldLabel: '目标字符串',
                            name: 'targetText'
                        },
                        {
                            xtype: 'button',
                            x: 140,
                            y: 270,
                            height: 50,
                            width: 150,
                            text: '验证',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'image',
                            x: 310,
                            y: 270,
                            height: 50,
                            id: 'imgResult',
                            width: 70
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var regText=button.up('form').down('#regText').value;
        var targetText=button.up('form').down('#targetText').value;

        Ext.Ajax.request({
            url: '../../../system/checkRegText',
            params: {regText:regText,targetText:targetText},
            success: function(response, opts) {
                var obj = Ext.decode(response.responseText);
                if(obj.regMatched){
                    Ext.getCmp("imgResult").setSrc('images/yes.gif');
                }
                else{
                    Ext.getCmp("imgResult").setSrc('images/no.gif');
                }
            },
            failure: function(response, opts) {
            }
        });


    }

});