/*
 * File: app/view/ConfigPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.ConfigPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.configPanel',

    requires: [
        'app.view.PropertyGrid'
    ],

    id: 'configPanel',
    layout: {
        type: 'fit'
    },
    title: 'Config',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    headerPosition: 'left',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'fit'
                            },
                            title: avmon.equipmentCenter.CIProperty,
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnSaveProp',
                                            iconCls: 'icon-save',
                                            text: avmon.common.save
                                        },
                                        {
                                          xtype: 'hiddenfield',
                                          id: 'moId',
                                          width: 0,
                                          fieldLabel: 'Label'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'propertyGrid'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});