select 
t2.DEVICE_NM, 
t2.DEVICE_VERSION,
t2.DEVICE_TYPE,
t1.DEVICE_IP,
t1.USR, 
t1.PWD, 
t1.COMM_CODE,
t1.QUIT_MODE1 
from 
TF_AVMON_RI_DEVICE_COMM_MAP t1 
inner join TF_AVMON_ROUTE_INSPECT_DEVICE t2 on (t1.DEVICE_IP = t2.DEVICE_IP) 