/*
 * File: app/view/AddMoWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.AddMoWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.addMoWindow',

    height: 225,
    width: 354,
    layout: {
        type: 'fit'
    },
    closeAction: 'hide',
    title: avmon.deploy.addMonitorHost,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: avmon.deploy.monitoringObjectNumber,
                            name: 'id'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: avmon.deploy.hostName,
                            name: 'text'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: avmon.deploy.objectType,
                            name: 'type'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: avmon.deploy.ipaddress,
                            name: 'ip'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: avmon.deploy.operatingSystem,
                            name: 'os',
                            displayField: 'name',
                            queryMode: 'local',
                            store: 'HostTypeList',
                            valueField: 'name'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnAddHostOk',
                            iconCls: 'icon-ok',
                            text: avmon.common.ok
                        },
                        {
                            xtype: 'button',
                            id: 'btnAddHostCancel',
                            iconCls: 'icon-cancel',
                            text: avmon.common.cancel
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});