/*
 * File: app/view/ConfigPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.ConfigPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.configPanel',

    requires: [
        'app.view.PropertyGrid'
    ],

    id: 'configPanel',
    layout: {
        type: 'fit'
    },
    title: 'Config',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'panel',
                    dock: 'top',
                    frame: true,
                    height: 50,
                    hidden: true,
                    layout: {
                        type: 'absolute'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'displayfield',
                            x: 10,
                            y: 10,
                            id: 'agentStatus',
                            width: 160,
                            fieldLabel: avmon.deploy.agentStatus,
                            labelAlign: 'right',
                            labelWidth: 80,
                            value: avmon.deploy.unknown
                        },
                        {
                            xtype: 'displayfield',
                            x: 320,
                            y: 10,
                            id: 'agentLastUpdateTime',
                            width: 300,
                            fieldLabel: 'Agent最后更新时间',
                            labelAlign: 'right',
                            labelWidth: 150,
                            value: avmon.deploy.unknown
                        },
                        {
                            xtype: 'button',
                            x: 180,
                            y: 10,
                            id: 'btnPauseAgent',
                            width: 50,
                            iconCls: 'icon-pause',
                            text: avmon.deploy.hangUp
                        },
                        {
                            xtype: 'button',
                            x: 240,
                            y: 10,
                            id: 'btnStartAgent',
                            width: 50,
                            iconCls: 'icon-start',
                            text: avmon.deploy.restore
                        },
                        {
                            xtype: 'hiddenfield',
                            id: 'moId',
                            width: 0,
                            fieldLabel: 'Label'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    headerPosition: 'left',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'fit'
                            },
                            title: avmon.deploy.CIProperty,
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnSaveProp',
                                            iconCls: 'icon-save',
                                            text: avmon.common.save
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'propertyGrid'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});