/*
 * File: app/store/KpiValues.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.store.KpiValuesz03', {
    extend: 'Ext.data.Store',

    requires: [
        'app.model.KpiValuez'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
        	autoLoad: false,
            model: 'app.model.KpiValuez',
            storeId: 'KpiValuesz03',
            groupField: 'AMP_INSTANCE_NAME',
            proxy: {
                type: 'ajax',
                extraParams: {
                    mo: 'None'
                },
                url: '../../performance/kpiValueListz03',
                reader: {
                    type: 'json',
                    root: 'activeData009',
                }
            }
        }, cfg)]);
    }
});