/*
 * File: app/model/Monitor.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.model.Monitor', {
    extend: 'Ext.data.Model',

    idProperty: 'path',

    fields: [
        {
            name: 'path'
        },
        {
            name: 'name'
        },
        {
            name: 'caption'
        },
        {
            name: 'version'
        },
        {
            name: 'status'
        },
        {
            name: 'schedule1'
        },
        {
            name: 'schedule2'
        },
        {
            name: 'schedule3'
        },
        {
            name: 'schedule4'
        },
        {
            name: 'schedule5'
        },
        {
            name: 'schedule6'
        },
        {
            name: 'scheduleType'
        },
        {
            name: 'deploy'
        },
        {
            name: 'latestVersion'
        },
        {
            name: 'moId'
        },
        {
            name: 'agentId'
        },
        {
            name: 'os'
        },
        {
            name: 'osVersion'
        },
        {
            name: 'ip'
        },
        {
            name: 'hostName'
        }
    ]
});