/*
 * File: app/../view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('login.view.LoginPanel', {
    extend: 'Ext.panel.Panel',

    border: 0,
    frame: false,
    height: 742,
    width: 1163,
    layout: {
        align: 'stretch',
        pack: 'center',
        type: 'vbox'
    },
    bodyCls: 'login-background',
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1
                },
                {
                    xtype: 'container',
                    height: 300,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1.3
                        },
                        {
                            xtype: 'form',
                            border: 0,
                            frame: true,
                            padding: 0,
                            width: 484,
                            layout: {
                                type: 'absolute'
                            },
                            frameHeader: false,
                            items: [
                                {
                                    xtype: 'image',
                                    height: 114,
                                    width: 484,
                                    src: '../resources/images/login_banner.png'
                                },
                                {
                                    xtype: 'textfield',
                                    x: 40,
                                    y: 130,
                                    width: 360,
                                    name: 'userId',
                                    fieldLabel: '用户ID',
                                    labelAlign: 'right',
                                    labelPad: 20,
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'textfield',
                                    x: 40,
                                    y: 170,
                                    width: 360,
                                    inputType: 'password',
                                    name: 'password',
                                    fieldLabel: '密码',
                                    labelAlign: 'right',
                                    labelPad: 20,
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    x: 310,
                                    y: 200,
                                    width: 90,
                                    name: 'theme',
                                    fieldLabel: '',
                                    labelAlign: 'right',
                                    labelPad: 20,
                                    labelSeparator: ' ',
                                    displayField: 'display',
                                    store: {
                                        fields: [
                                            'value',
                                            'display'
                                        ],
                                        data: [
                                            {
                                                value: '',
                                                display: '默认主题'
                                            },
                                            {
                                                value: '-gray',
                                                display: '灰色主题'
                                            },
                                            {
                                                value: '-access',
                                                display: '黑色主题'
                                            },
                                            {
                                                value: '-neptune',
                                                display: '简洁(测试)'
                                            }
                                        ]
                                    },
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'button',
                                    x: 70,
                                    y: 240,
                                    height: 30,
                                    width: 100,
                                    text: '登录',
                                    type: 'submit',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    x: 190,
                                    y: 240,
                                    height: 30,
                                    width: 100,
                                    text: '重置',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick1,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 130,
                                    y: 200,
                                    name: 'ckSavePass',
                                    fieldLabel: '',
                                    boxLabel: '在本地保存密码'
                                },
                                {
                                    xtype: 'button',
                                    x: 310,
                                    y: 240,
                                    height: 30,
                                    width: 90,
                                    text: 'License注册',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick2,
                                            scope: me
                                        }
                                    }
                                }
                            ],
                            listeners: {
                                afterrender: {
                                    fn: me.onFormAfterRender,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {

        button.disable();
        var userId=button.up("form").getForm().findField('userId').getValue();
        var password=button.up("form").getForm().findField('password').getValue();
        var savePass=button.up("form").getForm().findField('ckSavePass').getValue();
        var theme=button.up("form").getForm().findField('theme').getValue();


        Ext.Ajax.request({
            url: '../login',
            params: {userId:userId,password:password},
            success: function(response, opts) {
                var obj=Ext.decode(response.responseText);
                if(obj.errorMsg){
                    Ext.Msg.alert("登录失败",obj.errorMsg);
                }
                else{
                	Ext.avmon={};
                    Ext.avmon.loginUserId=obj.userId;
                    Ext.avmon.loginUserName=obj.userName;
                    showMainWindow(theme);
                    //alert(Ext.avmon.loginUserId);

                    /*
                    if(!Ext.avmon.main.frame){
                    Ext.avmon.main.frame=Ext.getCmp("mainFrame");
                    }
                    if(Ext.avmon.main.frame){
                    Ext.avmon.main.topView.removeAll();
                    Ext.avmon.main.topView.add(Ext.avmon.main.frame);
                    }
                    //*/
                }
                if(savePass){
                    Ext.util.Cookies.set('avmon.pass',password, new Date(new Date().getTime()+(1000*60*60*24*365)));
                }
                else{
                    Ext.util.Cookies.set('avmon.pass','', new Date(new Date().getTime()+(1000*60*60*24*365)));
                }
                Ext.util.Cookies.set('avmon.userid',userId, new Date(new Date().getTime()+(1000*60*60*24*365)));
                Ext.util.Cookies.set('avmon.theme',theme, new Date(new Date().getTime()+(1000*60*60*24*365)));

                button.enable();
            },
            failure: function(response, opts) {
                Ext.MessageBox.alert("错误","发生错误，请稍候再试！");
                button.enable();
            }
        });

    },

    onButtonClick1: function(button, e, options) {
        button.up("form").getForm().reset();

    },

    onFormAfterRender: function(abstractcomponent, options) {
        this.down("form").getForm().findField('userId').setValue("admin");
        var lastUserId=Ext.util.Cookies.get('avmon.userid');
        var lastPassword=Ext.util.Cookies.get('avmon.pass');
        var theme=Ext.util.Cookies.get('avmon.theme');

        if(lastUserId!=null){
            this.down("form").getForm().findField('userId').setValue(lastUserId);
            this.down("form").getForm().findField('password').focus();
        }
        else{
            this.down("form").getForm().findField('userId').focus();
        }
        //alert(lastPassword);
        if(lastPassword!=null){
            this.down("form").getForm().findField('password').setValue(lastPassword);
            //alert(this.down("form").getForm().findField('ckSavePass').getValue());
            this.down("form").getForm().findField('ckSavePass').setValue(true);
        }

        if(theme!=null){
            this.down("form").getForm().findField('theme').setValue(theme);
        }
        else{
            this.down("form").getForm().findField('theme').setValue("");
        }



    },

    onButtonClick2: function(button, e, options) {

        Ext.Ajax.request({
            url: '../getRegCode',
            params: {userId:userId,password:password},
            success: function(response, opts) {

                var obj=Ext.decode(response.responseText);

                var editForm = Ext.create('Ext.form.Panel', {
                    bodyPadding: 5,
                    border: false,
                    frame: true,
                    buttonAlign: 'center',
                    xtype: 'filedset',
                    url: '../registLicense',
                    defaultType: 'textfield',
                    items: [
                    {
                        labelStyle : 'text-align:right;width:80;',
                        width:340,
                        fieldLabel: '初始注册码',
                        name: 'regCode',
                        fieldStyle:'padding-top:3px;background:none; border-right: 0px solid;border-top: 0px solid;border-left: 0px solid;border-bottom: #000000 0px solid;',
                        value:obj.regCode,
                        allowBlank: false
                    }
                    ,{
                        labelStyle : 'text-align:right;width:80;',
                        width:340,
                        fieldLabel: '注册码',
                        name: 'license',
                        allowBlank: false
                    }
                    ],
                    buttons: [{
                        text: '注册',
                        formBind: true, //only enabled once the form is valid
                        disabled: true,
                        iconCls:'icon-save',
                        handler: function() {
                            var submitForm = this.up('form').getForm();
                            if (submitForm.isValid()) {
                                submitForm.submit({
                                    method: 'POST',
                                    waitMsg:'正在注册，请稍等...',
                                    success: function(form, action) {
                                        Ext.MessageBox.alert('提示', action.result.msg,function(){eidtWin.close();});

                                    }
                                });
                            }
                        }
                    },{
                        text: '关闭',
                        iconCls:'icon-close',
                        handler: function() {
                            eidtWin.close();
                        }
                    }]
                });
                var eidtWin = Ext.create('Ext.window.Window',{
                    title: '注册License',
                    height: 150,
                    width:400,
                    hidden: true,
                    iconCls:'icon-form',
                    layout: 'fit',
                    plain: true,
                    modal:true,
                    closable: true,
                    closeAction: 'hide',
                    items: [editForm]
                });

                eidtWin.show();

            },
            failure: function(response, opts) {
                Ext.MessageBox.alert("错误","发生错误，请稍候再试！");
            }
        });
    }

});