/*
 * File: app/../view/ConfigPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('test.view.ConfigPanel', {
    extend: 'Ext.panel.Panel',

    activeItem: 1,
    height: 496,
    id: 'mainpanel',
    width: 690,
    layout: {
        type: 'card'
    },
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'panel2',
                    title: 'panel2'
                },
                {
                    xtype: 'panel',
                    itemId: 'panel1',
                    title: 'panel1',
                    items: [
                        {
                            xtype: 'button',
                            height: 101,
                            width: 243,
                            text: 'add menu',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'label',
                            style: 'font-weight:bold;',
                            text: 'My Labe    l         '
                        },
                        {
                            xtype: 'tbspacer',
                            width: 30
                        },
                        {
                            xtype: 'button',
                            allowDepress: false,
                            enableToggle: true,
                            pressed: true,
                            text: 'MyButton',
                            toggleGroup: 'aaa'
                        },
                        {
                            xtype: 'button',
                            baseCls: 'x-btn x-btn-over',
                            allowDepress: false,
                            enableToggle: true,
                            text: 'MyButton',
                            toggleGroup: 'aaa',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            allowDepress: false,
                            enableToggle: true,
                            text: 'MyButton',
                            toggleGroup: 'aaa'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick1: function(button, e, options) {

    },

    onButtonClick: function(button, e, options) {
        var main=Ext.getCmp("mainpanel");
        var toolbar=main.down("toolbar");
        var button=Ext.create("Ext.Button", {
            text: "事件实现1",
            allowDepress: false, 
            toggleGroup: 'aaa',
            enableToggle: true, 
            handler: function () {
                Ext.Msg.alert("提示", "第一个事件");
            }
        });

        var button2=Ext.create("Ext.Button", {
            text: "事件实现2",
            allowDepress: false, 
            toggleGroup: 'aaa',
            enableToggle: true, 
            handler: function () {
                Ext.Msg.alert("提示", "第2个事件");
            }
        });

        toolbar.add(button);

        toolbar.add(button2);
        alert(1);
        button.hide();
        alert(2);
        button.show();

    }

});