/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [{
                xtype: 'panel',
                region: 'north',
                border: 0,
                height: 70,
                id: 'topPanel',
                layout: {
                    type: 'fit'
                },
                bodyBorder: false,
                items: [
                    {
                        xtype: 'panel',
                        border: 0,
                        height: 70,
                        id: 'mainMenuPanel',
                        autoScroll: false,
                        layout: {
                            type: 'absolute'
                        },
                        bodyBorder: false,
                        html:"<div id=\"top\" class=\"top\"><div class=\"fixed\">" +
                		"<a href=\"../main\"><div class=\"Avmon_back_gif\" style=\"width:48px;height:43px\" >" +
                		"<img id=\"Avmon_back_img\" src=\"../resources/images/back.png\" " +
                		" onmouseover=\"mouseover('..');\" onmouseout=\"mouseout('..');\" ></div></a>" +
                		"<div class=\"MainTitle f28px LineH12\"  style=\"font-family: \'Microsoft yahei\',\'微软雅黑\',\'Lato\', Helvetica,Tahoma,Verdana,Arial,sans-serif \" >性能分析</div>"
                    }
                ]
            },
                {
                    xtype: 'treepanel',
                    region: 'west',
                    id: 'performanceTree',
                    itemId: 'performanceTree',
                    width: 250,
                    collapsible: true,
                    title: 'Menu',
                    store: 'PerformanceMenus',
                    rootVisible: false,
                    viewConfig: {

                    },
                    listeners: {
                        select: {
                            fn: me.onPerformanceTreeSelect,
                            scope: me
                        },
                        afterlayout: {
                            fn: me.onPerformanceTreeAfterLayout,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    id: 'performanceContent'
                }
            ]
        });

        me.callParent(arguments);
    },

    onPerformanceTreeSelect: function(rowmodel, record, index, eOpts) {
        Ext.getCmp('performanceContent').body.update('<iframe scrolling="auto" frameborder="0" width="100%" height="100%" src="'+record.get("url")+'"></iframe>');
    },

    onPerformanceTreeAfterLayout: function(container, layout, eOpts) {
        var tree=Ext.getCmp("performanceTree");
        var path="/root/" + tree.getRootNode().firstChild.internalId;
        tree.expandPath(path, 'id', '/', function(bSuccess, oLastNode){
            if(bSuccess){
                tree.getSelectionModel().select(oLastNode,true);
            }
            else{
                //alert('未找到节点'+moId);
            }
        });
    }

});